# Generated by Django 6.0.6 on 2026-07-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_datas_pimg_alter_datas_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='pimg',
        ),
    ]
